<a href="https://colab.research.google.com/github/01aleem/Hotel-Booking-Analysis/blob/main/Hotel_Booking_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <b> Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions!

## <b>This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally identifying information has been removed from the data. </b>

## <b> Explore and analyze the data to discover important factors that govern the bookings. </b>

In [2]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [26]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AlmaBetter/Capstone Projects/EDA/Hotel Bookings.csv')

In [4]:
df.head()

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]

In [5]:
df.shape

(119390, 32)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [7]:
df.arrival_date_year.unique()

array([2015, 2016, 2017])

In [8]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [10]:
type(df.loc[0,'arrival_date_month'])

str

In [11]:
type(df.loc[0,'arrival_date_day_of_month'])

numpy.int64

In [13]:
df['date_of_arrival'] = str(df['arrival_date_day_of_month']) + df['arrival_date_month'] + str(df['arrival_date_year'])

In [14]:
df.head()

hotel  ...                                    date_of_arrival
0  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
1  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
2  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
3  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
4  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...

[5 rows x 33 columns]

In [16]:
df['arrival_date_month'].unique()

array(['July', 'August', 'September', 'October', 'November', 'December',
       'January', 'February', 'March', 'April', 'May', 'June'],
      dtype=object)

In [17]:
from datetime import datetime

In [28]:
df['arrival_date_month'] = df['arrival_date_month'].apply(lambda x: datetime.strptime(x, '%B'))

In [19]:
df['arrival_date_month'].unique()

array(['1900-07-01T00:00:00.000000000', '1900-08-01T00:00:00.000000000',
       '1900-09-01T00:00:00.000000000', '1900-10-01T00:00:00.000000000',
       '1900-11-01T00:00:00.000000000', '1900-12-01T00:00:00.000000000',
       '1900-01-01T00:00:00.000000000', '1900-02-01T00:00:00.000000000',
       '1900-03-01T00:00:00.000000000', '1900-04-01T00:00:00.000000000',
       '1900-05-01T00:00:00.000000000', '1900-06-01T00:00:00.000000000'],
      dtype='datetime64[ns]')

In [29]:
df['arrival_date_month'] = df['arrival_date_month'].apply(lambda x: x.month)

In [30]:
df['arrival_date_month'].unique()

array([ 7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6])

In [31]:
df.head()

hotel  is_canceled  ...  reservation_status  reservation_status_date
0  Resort Hotel            0  ...           Check-Out               2015-07-01
1  Resort Hotel            0  ...           Check-Out               2015-07-01
2  Resort Hotel            0  ...           Check-Out               2015-07-02
3  Resort Hotel            0  ...           Check-Out               2015-07-02
4  Resort Hotel            0  ...           Check-Out               2015-07-03

[5 rows x 32 columns]

In [33]:
df.head()


hotel  ...                                    date_of_arrival
0  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
1  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
2  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
3  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...
4  Resort Hotel  ...  0          1\n1          1\n2          1\n3   ...

[5 rows x 33 columns]

In [39]:
df['date'] = df["arrival_date_day_of_month"].astype(str) + '-' + df["arrival_date_month"].astype(str) + '-' + df["arrival_date_year"].astype(str)

In [40]:
df.head()

hotel  ...      date
0  Resort Hotel  ...  1-7-2015
1  Resort Hotel  ...  1-7-2015
2  Resort Hotel  ...  1-7-2015
3  Resort Hotel  ...  1-7-2015
4  Resort Hotel  ...  1-7-2015

[5 rows x 34 columns]

In [43]:
df['date'] = df['date'].apply(lambda x: datetime.strptime(x, '%d-%m-%Y'))

In [44]:
df.head()

hotel  ...       date
0  Resort Hotel  ... 2015-07-01
1  Resort Hotel  ... 2015-07-01
2  Resort Hotel  ... 2015-07-01
3  Resort Hotel  ... 2015-07-01
4  Resort Hotel  ... 2015-07-01

[5 rows x 34 columns]

In [46]:
df.drop(columns = ['date_of_arrival'], inplace = True)

In [47]:
df.head()

hotel  is_canceled  ...  reservation_status_date       date
0  Resort Hotel            0  ...               2015-07-01 2015-07-01
1  Resort Hotel            0  ...               2015-07-01 2015-07-01
2  Resort Hotel            0  ...               2015-07-02 2015-07-01
3  Resort Hotel            0  ...               2015-07-02 2015-07-01
4  Resort Hotel            0  ...               2015-07-03 2015-07-01

[5 rows x 33 columns]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype         
---  ------                          --------------   -----         
 0   hotel                           119390 non-null  object        
 1   is_canceled                     119390 non-null  int64         
 2   lead_time                       119390 non-null  int64         
 3   arrival_date_year               119390 non-null  int64         
 4   arrival_date_month              119390 non-null  int64         
 5   arrival_date_week_number        119390 non-null  int64         
 6   arrival_date_day_of_month       119390 non-null  int64         
 7   stays_in_weekend_nights         119390 non-null  int64         
 8   stays_in_week_nights            119390 non-null  int64         
 9   adults                          119390 non-null  int64         
 10  children                        119386 non-null  float64

In [51]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'date'],
      dtype='object')

In [52]:
df.rename(columns = {'is_canceled':'canceled', 'arrival_date_year':'year', 'arrival_date_month':'month', 'arrival_date_week_number':'week_of_month',
                     'is_repeated_guest': 'repeated_guest'}, inplace = True)

In [53]:
df.head()

hotel  canceled  ...  reservation_status_date       date
0  Resort Hotel         0  ...               2015-07-01 2015-07-01
1  Resort Hotel         0  ...               2015-07-01 2015-07-01
2  Resort Hotel         0  ...               2015-07-02 2015-07-01
3  Resort Hotel         0  ...               2015-07-02 2015-07-01
4  Resort Hotel         0  ...               2015-07-03 2015-07-01

[5 rows x 33 columns]

In [54]:
df.drop(columns = ['week_of_month'], inplace = True)

In [59]:
df['children'] = df['children'].astype('int')

ValueError: ignored

In [60]:
df.head()

hotel  canceled  ...  reservation_status_date       date
0  Resort Hotel         0  ...               2015-07-01 2015-07-01
1  Resort Hotel         0  ...               2015-07-01 2015-07-01
2  Resort Hotel         0  ...               2015-07-02 2015-07-01
3  Resort Hotel         0  ...               2015-07-02 2015-07-01
4  Resort Hotel         0  ...               2015-07-03 2015-07-01

[5 rows x 32 columns]

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype         
---  ------                          --------------   -----         
 0   hotel                           119390 non-null  object        
 1   canceled                        119390 non-null  int64         
 2   lead_time                       119390 non-null  int64         
 3   year                            119390 non-null  int64         
 4   month                           119390 non-null  int64         
 5   arrival_date_day_of_month       119390 non-null  int64         
 6   stays_in_weekend_nights         119390 non-null  int64         
 7   stays_in_week_nights            119390 non-null  int64         
 8   adults                          119390 non-null  int64         
 9   children                        119386 non-null  float64       
 10  babies                          119390 non-null  int64  

In [63]:
df['children'].unique()

array([ 0.,  1.,  2., 10.,  3., nan])

In [64]:
df.children.isnull().sum()

4

In [65]:
df['children'].value_counts()

0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: children, dtype: int64

In [66]:
df['children'] = df['children'].fillna(0)

In [67]:
df['children'].value_counts()

0.0     110800
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: children, dtype: int64

In [68]:
df['children'] = df['children'].astype('int')

In [69]:
df.head()

hotel  canceled  ...  reservation_status_date       date
0  Resort Hotel         0  ...               2015-07-01 2015-07-01
1  Resort Hotel         0  ...               2015-07-01 2015-07-01
2  Resort Hotel         0  ...               2015-07-02 2015-07-01
3  Resort Hotel         0  ...               2015-07-02 2015-07-01
4  Resort Hotel         0  ...               2015-07-03 2015-07-01

[5 rows x 32 columns]